name: longplex-nf-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::nextflow=23.10.1
  - conda-forge::python=3.11.0
  - conda-forge::pytest=7.2.0
  - conda-forge::pip=22.3.1
  - pip:
    - pytest-workflow==2.0.1
    - latch==2.55.2
